#!/bin/sh

# SilverStripe Framework App Boilerplate
#
# Installation helper for unix based operation systems. To setup a new app with
# the bootstrap run the following
#
# bash <(curl -s https://raw.githubusercontent.com/fullscreeninteractive/silverstripe-boilerplate/master/install)
#
# And follow the prompts

TEMP_PATH="/tmp/fsi_sfab"

command -v git >/dev/null 2>&1 || { 
	echo "git is required to download the SilverStripe Framework. Aborting." >&2; exit 1; 
}

command -v composer >/dev/null 2>&1 || {
	echo "--> Installing Composer"
	@curl -sS https://getcomposer.org/installer | php
	@mv composer.phar /usr/local/bin/composer.phar
}


echo "Enter the path for your new SilverStripe project (e.g ~/Sites/app):";
read INSTALL_PATH

if [ -d "$INSTALL_PATH" ]; then
	echo "$INSTALL_PATH exists, cannot install to existing folder";

	exit
fi

echo "Which boilerplate template would you like to start with (cms, framework, foundation)";
read BRANCH_NAME

if [ "$BRANCH_NAME" = 'framework' ]; then
	BRANCH_NAME='master'
fi

if [ -d "$TEMP_PATH" ]; then
	echo "--> Updating SilverStripe Framework Boilerplate"

	cd $TEMP_PATH
	git fetch -q origin
	git clean -f -d -q
else
	echo "--> Installing SilverStripe Framework Boilerplate"

	git clone -q git@github.com:wilr/silverstripe-framework-app-boilerplate.git $TEMP_PATH
	cd $TEMP_PATH
fi


exists=`git show-ref remotes/origin/$BRANCH_NAME`

if [ ! -n "$exists" ]; then
	echo "Template $BRANCH_NAME does not exist in the boilerplate. Try cms"
	exit
fi


git reset --hard -q origin/$BRANCH_NAME
cd - >/dev/null

echo "--> Linking SilverStripe Boilerplate"

if [[ "$INSTALL_PATH" == \~*/* || "$INSTALL_PATH" == \~ || "$INSTALL_PATH" == \~/* || "$INSTALL_PATH" == \~/ ]]; then
	INSTALL_PATH="${HOME}${INSTALL_PATH:1:${#INSTALL_PATH}}"
fi

cp -R $TEMP_PATH $INSTALL_PATH


if [ -d "$INSTALL_PATH" ]; then
	echo "--> Cleaning up SilverStripe Boilerplate"
	cd $INSTALL_PATH
	rm -rf .git install README.md LICENSE.md

	echo "--> Pulling silverstripe-framework in via Composer"
	composer update -q

	command -v sake >/dev/null 2>&1 || {
		echo "--> Installing Sake"
		./framework/sake installsake
	}

	cd - >/dev/null
else 
	echo "--> Error installing SilverStripe Boilerplate"
fi

echo "--> Done."
